### ISSUE TITLE
fast scrolling down throwing NoSuchFieldException

### ISSUE THREAD

**Issue by satya-kodukula** [mukeshsolanki/country-picker-android#1]
E/CountryCodePicker: Failure to get drawable id.
                                                                                        java.lang.NoSuchFieldException: flag_bl
                                                                                            at java.lang.Class.getField(Class.java:891)
                                                                                            at com.mukesh.countrypicker.adapters.CountryListAdapter.getResId(CountryListAdapter.java:30)
                                                                                            at com.mukesh.countrypicker.adapters.CountryListAdapter.getView(CountryListAdapter.java:76)
                                                                                            at android.widget.AbsListView.obtainView(AbsListView.java:2346)
                                                                                            at android.widget.ListView.makeAndAddView(ListView.java:1875)
                                                                                            at android.widget.ListView.fillDown(ListView.java:702)
                                                                                            at android.widget.ListView.fillGap(ListView.java:666)
                                                                                            at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5029)
                                                                                            at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4577)
                                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                            at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by hilzinju** [comment]
Flag icon from Saint-Barthélemy is missing

**Comment by mukeshsolanki** [comment]
@hilzinju thanks for that we have updated and fixed it :)

**Comment by satya-kodukula** [comment]
Looks good, Thank you!
