### ISSUE TITLE
Find crash on changing 5 to 6 times by picing country

### ISSUE THREAD

**Issue by ashishCDN0135** [mukeshsolanki/country-picker-android#25]
FATAL EXCEPTION: main
                                                              java.lang.IllegalStateException: Fragment already added: CountryPicker{5321ceb8 #0 COUNTRY_PICKER}
                                                                  at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1679)
                                                                  at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:727)
                                                                  at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                  at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                  at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                  at android.os.Handler.handleCallback(Handler.java:730)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                  at android.os.Looper.loop(Looper.java:137)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:525)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                  at dalvik.system.NativeStart.main(Native Method)

**Comment by mukeshsolanki** [comment]
does not seem to crash can you share your code?

**Comment by mukeshsolanki** [comment]
no response
