### ISSUE TITLE
CraSh on Click of Spinner

### ISSUE THREAD

**Issue by ntaditi** [mukeshsolanki/country-picker-android#27]
java.lang.NoSuchFieldError: No static field row_title of type I in class Lcom/mukesh/countrypicker/R$id; or its superclasses (declaration of 'com.mukesh.countrypicker.R$id' appears in /data/app/in.ticketninja.test-gy1ogBf0PImNXdeOb5B9_A==/base.apk)
                                                                       at com.mukesh.countrypicker.CountryListAdapter$Cell.from(CountryListAdapter.java:70)
                                                                       at com.mukesh.countrypicker.CountryListAdapter.getView(CountryListAdapter.java:51)
                                                                       at android.widget.AbsListView.obtainView(AbsListView.java:2372)
                                                                       at android.widget.ListView.measureHeightOfChildren(ListView.java:1408)
                                                                       at android.widget.ListView.onMeasure(ListView.java:1315)
                                                                       at android.view.View.measure(View.java:21998)
                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
                                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
                                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
                                                                       at android.view.View.measure(View.java:21998)
                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                       at android.view.View.measure(View.java:21998)
                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                       at android.view.View.measure(View.java:21998)
                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:721)
                                                                       at android.view.View.measure(View.java:21998)
                                                                       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2410)
                                                                       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1471)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1751)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:658)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                       at android.os.Handler.handleCallback(Handler.java:789)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                       at android.os.Looper.loop(Looper.java:164)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by mukeshsolanki** [comment]
What exactly are you trying to do?

**Comment by mukeshsolanki** [comment]
no response
